### ISSUE TITLE
heapSort

### ISSUE THREAD

**Issue by Cgarg9** [Cgarg9/basic_dsa_cpp#9]
Implement the heapSort algorithm in cpp.

**Comment by GitMasterJatin** [comment]
I want to be assigned this issue

**Comment by Cgarg9** [comment]
done

**Comment by AmethystMac** [comment]
Hi, is this done?

**Comment by Cgarg9** [comment]
@AmethystMac  No. Please follow the template in /searching/bookAllocation.cpp.
Make  a solution class and include the same headers. Push the code into the sorting folder

**Comment by AmethystMac** [comment]
Hey @Cgarg9, I have sent a PR for Heap Sort. Take a look

**Comment by Cgarg9** [comment]
@AmethystMac merged the PR. Well done
